Kenyahmis toolbox
palladiumkenya/kenyaemr-autoupdate pull request #2
Opened 2022-08-11 15:21 UTC by Rugute

Implemented automatic updates for all the apps using application.properties.

2022-08-11 19:59 UTC, ojwanganto requested changes

2022-08-11 19:59 UTC, ojwanganto commented on src/main/java/com/kenyahmis/applicationtoolkit/controllers/ToolboxController.java
> +        String downloadUrl = remoteurl;//  "https://github.com/palladiumkenya/kenyahmis-releases/releases/download/v51/KenyaEMR_18.2.0.zip";
we can remove the commented code. I think the variable is self explanatory

2022-08-11 19:59 UTC, ojwanganto commented on src/main/java/com/kenyahmis/applicationtoolkit/controllers/ToolboxController.java
> +        System.out.println(prop.getProperty("toolkit.emrurl"));
we can remove the logs

2022-08-11 19:59 UTC, ojwanganto commented on src/main/java/com/kenyahmis/applicationtoolkit/controllers/ToolboxController.java
> +        remoteproperties=prop.getProperty("toolkit.remoteproperties");
we can add some documentation that explains more about the properties.

2022-08-11 19:59 UTC, ojwanganto commented on src/main/resources/application.properties
> +toolkit.emrurl = https://github.com/palladiumkenya/kenyahmis-releases/releases/download/v51/KenyaEMR_18.2.0.zip
do you think we can qualify this to toolkit.kenyaemrpackageurl?

2022-08-11 19:59 UTC, ojwanganto commented on src/main/resources/application.properties
> +toolkit.remoteproperties=https://github.com/Rugute/kenyaemr-autoupdate/blob/kenyahmis-toolbox/src/main/resources/application.properties
use the palladiumkenya repo for this. I know this was meant for testing

2022-08-11 19:59 UTC, ojwanganto commented on src/main/resources/application.properties
> +toolkit.localproperties=/opt/kehmisApplicationToolbox/application.properties
We can conventionally use a static relative path so that we don't need this property i.e. applicationDir/application.properties. You don't have to change this now

2022-08-11 19:59 UTC, ojwanganto commented on src/main/resources/application.properties
> +toolkit.emrversion = 1.8.2
is this the currently deployed or the version to be updated?

2022-08-12 05:12 UTC, Rugute commented on src/main/java/com/kenyahmis/applicationtoolkit/controllers/ToolboxController.java
> +        String downloadUrl = remoteurl;//  "https://github.com/palladiumkenya/kenyahmis-releases/releases/download/v51/KenyaEMR_18.2.0.zip";
Ok

2022-08-12 05:12 UTC, Rugute commented on src/main/java/com/kenyahmis/applicationtoolkit/controllers/ToolboxController.java
> +        System.out.println(prop.getProperty("toolkit.emrurl"));
Sure

2022-08-12 05:13 UTC, Rugute commented on src/main/resources/application.properties
> +toolkit.emrurl = https://github.com/palladiumkenya/kenyahmis-releases/releases/download/v51/KenyaEMR_18.2.0.zip
sure

2022-08-12 05:13 UTC, Rugute commented on src/main/resources/application.properties
> +toolkit.remoteproperties=https://github.com/Rugute/kenyaemr-autoupdate/blob/kenyahmis-toolbox/src/main/resources/application.properties
Sure, once we merge this code will pick it palladiumkenya

2022-08-12 05:14 UTC, Rugute commented on src/main/resources/application.properties
> +toolkit.localproperties=/opt/kehmisApplicationToolbox/application.properties
Ok

2022-08-12 05:15 UTC, Rugute commented on src/main/resources/application.properties
> +toolkit.emrversion = 1.8.2
Was testing version change listener

2022-08-12 10:04 UTC, merged